import Head from "next/head";
import Sidebar from "../components/Sidebar.js";
import { auth } from "../firebase.js"

export default function Home() {
  const signOut = () => {
    auth.signOut()
  }
  return (
    <div>
      <Head>
        <title>Whatsapp 3.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href={
          "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/WhatsApp.svg/479px-WhatsApp.svg.png"
        } />
      </Head>
      <Sidebar />
    </div>
  );
}
